<template>
  <div>
    <b>KiCAD project generator:</b>
  </div>
  <div>
  Upload layout file generated by
  <b>
    <a href="http://www.keyboard-layout-editor.com">keyboard-layout-editor</a>
  </b>:
  <p/>
  </div>
  <div class="container">
    <el-button type="primary" @click="triggerUpload()">Upload layout <i class="el-icon-upload el-icon-right"></i></el-button>
    <el-progress :stroke-width="4" :percentage="progressBarPercentage" :status="progressBarStatus" :color="'#409eff'" v-if="taskId !== null"></el-progress>
    <a v-bind:href="apiEndpoint + '/' + taskId + '/result'" v-if="taskStatus === 'SUCCESS'">download!</a>
    <input type="file" id="file" ref="file" v-on:change="uploadLayout()" style="display:none"/>
  </div>
</template>

<script>
import axios from 'axios'

export default {
  name: 'KicadHandler',
  data() {
    return {
      apiEndpoint: `${process.env.VUE_APP_API_URL}/api/pcb`,
      taskId: null,
      taskStatus: null,
      progressBarStatus: "",
      progressBarPercentage: 0,
      polling: null
    }
  },
  methods: {
    triggerUpload() {
      this.progressBarStatus = "";
      this.progressBarPercentage = 0;
      this.$refs.file.click();
    },
    getTaskStatus() {
      axios.get(`${this.apiEndpoint}/${this.taskId}`)
           .then(res => {
             console.log(res.data);
             this.taskStatus = res.data.task_status;
             this.progressBarPercentage = res.data.task_result.percentage;
             if (this.taskStatus !== "PENDING" && this.taskStatus !== "PROGRESS") {
               if (this.taskStatus !== "SUCCESS") {
                 this.progressBarPercentage = 100;
                 this.progressBarStatus = "exception";
               }
               clearInterval(this.polling);
             }
           })
           .catch(() => {
             this.progressBarPercentage = 100;
             this.progressBarStatus = "exception";
             clearInterval(this.polling);
           });
    },
    uploadLayout() {
      var kle = require('@ijprest/kle-serial');

      let file = this.$refs.file.files[0];

      let reader = new FileReader();
      reader.readAsText(file, "UTF-8");
      reader.onload = evt => {
        const result = evt.target.result;
        const keyboard = kle.Serial.deserialize(JSON.parse(result));

        axios.post(`${this.apiEndpoint}`, keyboard)
             .then(res => {
               if (res.status === 202) {
                 this.taskId = res.data.task_id;

                 this.polling = setInterval(() => {
                   this.getTaskStatus();
                 }, 1000);
               }
             });
      }
      reader.onerror = evt => {
        console.error(evt);
      }
    }
  }
};
</script>

<style scoped>
</style>
