<template>
  <div>
    Upload json layout generated by <a href="http://www.keyboard-layout-editor.com">keyboard-layout-editor</a> with switch matrix coordinates:
  </div>
  <br>
  <PcbSettings @settings="handlePcbSettings" ref="pcbSettings"/>
  <br>
  <div>
    <el-button type="primary" @click="triggerUpload()">Upload layout <i class="el-icon-upload el-icon-right"></i></el-button>
    <input type="file" id="file" ref="file" accept=".json" v-on:change="uploadLayout()" style="display:none"/>
    <el-progress :stroke-width="4" :percentage="progressBarPercentage" :status="progressBarStatus" :color="'#409eff'" v-if="taskId !== null"></el-progress>
  </div>
  <br>
  <div>
    <img style="width: 100%; height: 100%" :src="`${svgData}`" v-if="svgData !== ''">
    <a id="download" v-bind:href="getResultUrl()" v-if="taskStatus === 'SUCCESS'">
      <el-button type="success">Download project</el-button>
    </a>
  </div>
</template>

<script>
import axios from 'axios'
import PcbSettings from '@/components/PcbSettings.vue'

export default {
  name: 'KicadHandler',
  data() {
    return {
      apiEndpoint: `${process.env.VUE_APP_API_URL}/api/pcb`,
      taskId: null,
      taskStatus: null,
      progressBarStatus: "",
      progressBarPercentage: 0,
      polling: null,
      svgData: "",
      pcbSettings: {},
    }
  },
  methods: {
    handlePcbSettings(params) {
      this.pcbSettings = params;
    },
    showFailAlert(message) {
      this.setProgressBarFailState();
      this.$alert(message, "Failed", {
        confirmButtonText: "OK",
        type: "error",
      });
    },
    triggerUpload() {
      this.taskStatus = null;
      this.progressBarStatus = "";
      this.progressBarPercentage = 0;
      this.svgData = "";
      this.$refs.file.click();
    },
    setProgressBarFailState() {
      this.progressBarPercentage = 100;
      this.progressBarStatus = "exception";
    },
    getTaskRender() {
      axios.get(`${this.apiEndpoint}/${this.taskId}/render`)
           .then(resp => {
             this.svgData = `data:image/svg+xml;base64,${resp.data}`;
           })
           .catch(() => {
             this.showFailAlert("Preview render not available");
           });
    },
    getTaskStatus() {
      axios.get(`${this.apiEndpoint}/${this.taskId}`)
           .then(res => {
             this.taskStatus = res.data.task_status;
             this.progressBarPercentage = res.data.task_result.percentage;
             if (this.taskStatus !== "PENDING" && this.taskStatus !== "PROGRESS") {
               if (this.taskStatus === "SUCCESS") {
                 this.getTaskRender();
               } else {
                 this.showFailAlert(res.data.task_result);
               }
               clearInterval(this.polling);
             }
           })
           .catch(() => {
             this.showFailAlert("Unexpected exception when fetching task status");
             clearInterval(this.polling);
           });
    },
    getResultUrl() {
      return `${this.apiEndpoint}/${this.taskId}/result`;
    },
    uploadLayout() {
      var kle = require('@ijprest/kle-serial');

      let file = this.$refs.file.files[0];

      let reader = new FileReader();
      reader.readAsText(file, "UTF-8");
      reader.onload = evt => {
        if (file.type !== "application/json") {
          this.showFailAlert("Unsupported file type");
          return;
        }

        let keyboard;
        try {
          const result = evt.target.result;
          keyboard = kle.Serial.deserialize(JSON.parse(result));
        } catch (error) {
          this.showFailAlert(error.toString());
          return;
        }

        this.$refs.pcbSettings.getSettings();

        axios.post(`${this.apiEndpoint}`, {"layout": keyboard, "settings": this.pcbSettings})
             .then(res => {
               if (res.status === 202) {
                 this.taskId = res.data.task_id;

                 this.polling = setInterval(() => {
                   this.getTaskStatus();
                 }, 1000);
               } else {
                 this.showFailAlert("Request rejected");
               }
             })
             .catch((error) => {
               if (error.response) {
                 const data = error.response.data;
                 if (data.error) {
                   this.showFailAlert(data.error);
                 } else {
                   this.showFailAlert("Unexpected error");
                 }
               } else {
                 this.showFailAlert("Unexpected error");
               }
             });
      }
      reader.onerror = evt => {
        console.error(evt);
      }
    }
  },
  components: { PcbSettings },
};
</script>

<style scoped>
</style>
