<template>
  <div>
    Convert json layout generated by <a href="http://www.keyboard-layout-editor.com">keyboard-layout-editor</a> to it's internal form:
  </div>
  <br>
  <div>
    <el-button type="primary" @click="triggerUpload()">Upload layout <i class="el-icon-upload el-icon-right"></i></el-button>
    <input type="file" id="file" ref="file" accept=".json" v-on:change="uploadLayout()" style="display:none"/>
  </div>
  <br>
  <div style="height:400px;" v-if="convertedLayout !== ''">
    <prism-editor class="kle-raw-input" v-model="convertedLayout" :highlight="highlighter" line-numbers readonly></prism-editor>
  </div>
  <br>
  <div>
    <el-button type="success" @click="getConvertedLayout()" v-if="convertedLayout !== ''">Download</el-button>
  </div>
</template>

<script>
import FileSaver from 'file-saver';
import { PrismEditor } from 'vue-prism-editor';
import 'vue-prism-editor/dist/prismeditor.min.css';

// import highlighting library
import { highlight, languages } from 'prismjs/components/prism-core';
import 'prismjs/components/prism-clike';
import 'prismjs/components/prism-javascript';
import 'prismjs/themes/prism-coy.css';

export default {
  name: 'KleConverter',
  components: {
    PrismEditor,
  },
  data() {
    return {
      convertedLayout: '',
      convertedLayoutFilename: '',
    }
  },
  methods: {
    highlighter(convertedLayout) {
      return highlight(convertedLayout, languages.js); // languages.<insert language> to return html with markup
    },
    showFailAlert(message) {
      this.$alert(message, "Failed", {
        confirmButtonText: "OK",
        type: "error",
      });
    },
    triggerUpload() {
      this.$refs.file.click();
    },
    uploadLayout() {
      this.convertedLayout = '';
      var kle = require('@ijprest/kle-serial');
      let file = this.$refs.file.files[0];

      let reader = new FileReader();
      reader.readAsText(file, "UTF-8");
      reader.onload = evt => {
        if (file.type !== "application/json") {
          this.showFailAlert("Unsupported file type");
          return;
        }

        this.convertedLayoutFilename = file.name.replace(/\.[^/.]+$/, "");
        const result = evt.target.result;
        try {
          const keyboard = kle.Serial.deserialize(JSON.parse(result));
          this.convertedLayout = JSON.stringify(keyboard, null, 2);
        } catch (error) {
          this.showFailAlert(error.toString());
        }
      }
      reader.onerror = evt => {
        console.error(evt);
      }

    },
    getConvertedLayout() {
      var blob = new Blob([this.convertedLayout], {type: "text/plain;charset=utf-8"});
      FileSaver.saveAs(blob, this.convertedLayoutFilename + "-converted.json");
    },
  },
};
</script>

<style scoped>
  .kle-raw-input {
    /* we dont use `language-` classes anymore so thats why we need to add background and text color manually */
    background: #f8f8f8;

    /* you must provide font-family font-size line-height. Example: */
    font-family: Fira code, Fira Mono, Consolas, Menlo, Courier, monospace;
    font-size: 14px;
    line-height: 1.5;
    padding: 5px;
  }

  /* optional class for removing the outline */
  .prism-editor__textarea:focus {
    outline: none;
  }
</style>
