<script setup>
import { reactive } from "vue";
import { ElMessageBox } from "element-plus";
import { UploadFilled } from "@element-plus/icons-vue";
import { PrismEditor } from "vue-prism-editor";
import FileSaver from "file-saver";
import * as kle from "@ijprest/kle-serial";
import "vue-prism-editor/dist/prismeditor.min.css";

// import highlighting library
import { highlight, languages } from "prismjs/components/prism-core";
import "prismjs/components/prism-clike";
import "prismjs/components/prism-javascript";
import "prismjs/themes/prism-coy.css";

const state = reactive({
  convertedLayout: "",
  convertedLayoutFilename: "",
});

function highlighter(convertedLayout) {
  return highlight(convertedLayout, languages.js);
}

function showFailAlert(message) {
  ElMessageBox.alert(message, "Failed", {
    confirmButtonText: "OK",
    type: "error",
  });
}

function triggerUpload() {
  document.getElementById("file").click();
}

function uploadLayout() {
  state.convertedLayout = "";
  let file = document.getElementById("file").files[0];

  let reader = new FileReader();
  reader.readAsText(file, "UTF-8");
  reader.onload = (evt) => {
    if (file.type !== "application/json") {
      showFailAlert("Unsupported file type");
      return;
    }

    state.convertedLayoutFilename = file.name.replace(/\.[^/.]+$/, "");
    const result = evt.target.result;
    try {
      const keyboard = kle.Serial.deserialize(JSON.parse(result));
      state.convertedLayout = JSON.stringify(keyboard, null, 2);
    } catch (error) {
      showFailAlert(error.toString());
    }
  };
  reader.onerror = (evt) => {
    console.error(evt);
  };
}

function getConvertedLayout() {
  var blob = new Blob([state.convertedLayout], {
    type: "text/plain;charset=utf-8",
  });
  FileSaver.saveAs(blob, state.convertedLayoutFilename + "-converted.json");
}
</script>

<template>
  <div>
    Convert json layout generated by
    <a href="http://www.keyboard-layout-editor.com">keyboard-layout-editor</a>
    to it's internal form:
  </div>
  <br />
  <div>
    <el-button type="primary" @click="triggerUpload" :icon="UploadFilled">
      Upload layout
    </el-button>
    <input
      type="file"
      id="file"
      accept=".json"
      v-on:change="uploadLayout"
      style="display: none" />
  </div>
  <br />
  <div style="height: 400px" v-if="state.convertedLayout !== ''">
    <prism-editor
      class="kle-raw-input"
      v-model="state.convertedLayout"
      :highlight="highlighter"
      line-numbers
      readonly></prism-editor>
  </div>
  <br />
  <div>
    <el-button
      type="success"
      @click="getConvertedLayout"
      v-if="state.convertedLayout !== ''"
      >Download</el-button
    >
  </div>
</template>

<style scoped>
.kle-raw-input {
  /* we dont use `language-` classes anymore so thats why we need to add background and text color manually */
  background: #f8f8f8;

  /* you must provide font-family font-size line-height. Example: */
  font-family: Fira code, Fira Mono, Consolas, Menlo, Courier, monospace;
  font-size: 14px;
  line-height: 1.5;
  padding: 5px;
}

/* optional class for removing the outline */
.prism-editor__textarea:focus {
  outline: none;
}
</style>
